# Generated by Django 4.0.5 on 2022-06-22 10:22

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Role_details',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role_name', models.CharField(max_length=255, null=True)),
                ('description', models.TextField(null=True)),
                ('dt', models.DateField(auto_now_add=True)),
                ('tm', models.TimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(default=django.utils.timezone.now)),
                ('status', models.CharField(max_length=255, null=True)),
                ('auth_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='User_details',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('employee_id', models.CharField(max_length=255, null=True)),
                ('name', models.CharField(max_length=255, null=True)),
                ('department', models.CharField(max_length=255, null=True)),
                ('branch', models.CharField(max_length=255, null=True)),
                ('username', models.CharField(max_length=255, null=True)),
                ('password', models.CharField(max_length=255, null=True)),
                ('dt', models.DateField(auto_now_add=True)),
                ('tm', models.TimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(default=django.utils.timezone.now)),
                ('status', models.CharField(max_length=255, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='User_Management',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=255, null=True)),
                ('password_option', models.CharField(choices=[('Automatic', 'Automatic'), ('Manual', 'Manual')], max_length=255, null=True)),
                ('password', models.CharField(max_length=255, null=True)),
                ('description', models.TextField(null=True)),
                ('password_expiration_status', models.CharField(choices=[('days', 'days'), ('none', 'none')], max_length=255, null=True)),
                ('password_effective_from_dt', models.DateField(null=True)),
                ('password_effective_to_dt', models.DateField(null=True)),
                ('employee_id', models.CharField(max_length=255, null=True)),
                ('employee_branch', models.CharField(max_length=255, null=True)),
                ('employee_department', models.CharField(max_length=255, null=True)),
                ('employee_name', models.CharField(max_length=255, null=True)),
                ('dt', models.DateField(auto_now_add=True)),
                ('tm', models.TimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(default=django.utils.timezone.now)),
                ('status', models.CharField(max_length=255, null=True)),
                ('add_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='user_management_add_by_user_id', to=settings.AUTH_USER_MODEL)),
                ('auth_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='user_management_user_login', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='user_role_mapping',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_dt', models.DateField(null=True)),
                ('end_dt', models.DateField(null=True)),
                ('description', models.TextField(null=True)),
                ('dt', models.DateField(auto_now_add=True)),
                ('tm', models.TimeField(auto_now_add=True)),
                ('status', models.CharField(max_length=255, null=True)),
                ('auth_user_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='user_role_mapping_auth_user_login', to=settings.AUTH_USER_MODEL)),
                ('role_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='user_role_mapping_role_id', to='super_admin.role_details')),
                ('user_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='user_role_mapping_user_id', to='super_admin.user_management')),
            ],
        ),
        migrations.CreateModel(
            name='User_leave_details',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('leave_type', models.CharField(max_length=255, null=True)),
                ('from_dt', models.DateField(null=True)),
                ('to_dt', models.DateField(null=True)),
                ('total_days', models.IntegerField(null=True)),
                ('available_leave', models.CharField(max_length=255, null=True)),
                ('reason', models.TextField(null=True)),
                ('attachment', models.FileField(null=True, upload_to='user_leave_attachment')),
                ('annual_contact_no', models.CharField(max_length=255, null=True)),
                ('name_of_replacer', models.CharField(max_length=255, null=True)),
                ('tiket_entitled', models.CharField(max_length=255, null=True)),
                ('destination', models.CharField(max_length=255, null=True)),
                ('onward_journey', models.DateField(null=True)),
                ('return_journey', models.DateField(null=True)),
                ('family_entry', models.CharField(max_length=255, null=True)),
                ('dt', models.DateField(auto_now_add=True)),
                ('tm', models.TimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(default=django.utils.timezone.now)),
                ('status', models.CharField(max_length=255, null=True)),
                ('user_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='User_leave_details_user_id', to='super_admin.user_details')),
            ],
        ),
        migrations.CreateModel(
            name='Role_permission_details',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('permission_name', models.CharField(max_length=255, null=True)),
                ('read', models.CharField(max_length=255, null=True)),
                ('write', models.CharField(max_length=255, null=True)),
                ('edit', models.CharField(max_length=255, null=True)),
                ('delete', models.CharField(max_length=255, null=True)),
                ('view_all', models.CharField(max_length=255, null=True)),
                ('manage_all', models.CharField(max_length=255, null=True)),
                ('dt', models.DateField(auto_now_add=True)),
                ('tm', models.TimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(default=django.utils.timezone.now)),
                ('status', models.CharField(max_length=255, null=True)),
                ('role_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='Role_permission_details_role_id', to='super_admin.role_details')),
            ],
        ),
    ]
