# Generated by Django 4.0.5 on 2022-06-23 05:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('super_admin', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user_management',
            name='odoo_id',
            field=models.CharField(max_length=555, null=True),
        ),
    ]
