# Generated by Django 4.0.5 on 2022-06-27 06:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('super_admin', '0002_user_management_odoo_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user_management',
            old_name='password_effective_from_dt',
            new_name='effective_from_dt',
        ),
        migrations.RenameField(
            model_name='user_management',
            old_name='password_effective_to_dt',
            new_name='effective_to_dt',
        ),
        migrations.AddField(
            model_name='user_management',
            name='password_expiration_end_date',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='user_management',
            name='password_expiration_total_days',
            field=models.IntegerField(null=True),
        ),
    ]
