# Generated by Django 4.0.5 on 2022-06-28 06:26

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('super_admin', '0003_rename_password_effective_from_dt_user_management_effective_from_dt_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='user_role_mapping_history',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_dt', models.DateField(null=True)),
                ('end_dt', models.DateField(null=True)),
                ('dt', models.DateField(auto_now_add=True)),
                ('tm', models.TimeField(auto_now_add=True)),
                ('status', models.CharField(max_length=255, null=True)),
                ('updated_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='user_role_mapping_history_updated_id', to=settings.AUTH_USER_MODEL)),
                ('user_role_mapping_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='user_role_mapping_history_mapping_id', to='super_admin.user_role_mapping')),
            ],
        ),
    ]
