# Generated by Django 4.0.5 on 2022-06-28 06:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('super_admin', '0004_user_role_mapping_history'),
    ]

    operations = [
        migrations.AddField(
            model_name='user_role_mapping_history',
            name='description',
            field=models.TextField(null=True),
        ),
    ]
