# Generated by Django 4.0.5 on 2022-06-28 09:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('super_admin', '0005_user_role_mapping_history_description'),
    ]

    operations = [
        migrations.CreateModel(
            name='odoo_api_request_token',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token', models.TextField(null=True)),
                ('dt', models.DateField(auto_now_add=True)),
                ('tm', models.TimeField(auto_now_add=True)),
                ('status', models.CharField(max_length=255, null=True)),
            ],
        ),
    ]
