# Generated by Django 4.0.5 on 2022-06-30 05:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('super_admin', '0006_odoo_api_request_token'),
    ]

    operations = [
        migrations.CreateModel(
            name='odoo_notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('notification_type', models.CharField(choices=[('leave_type', 'leave_type')], max_length=255, null=True)),
                ('message', models.TextField(null=True)),
                ('mapping_id', models.IntegerField(null=True)),
                ('dt', models.DateField(auto_now_add=True)),
                ('tm', models.TimeField(auto_now_add=True)),
                ('requested_from_dt', models.DateField(null=True)),
                ('requested_to_dt', models.DateField(null=True)),
                ('read_status', models.IntegerField(default=0)),
                ('status', models.CharField(max_length=255, null=True)),
            ],
        ),
    ]
