# Generated by Django 4.0.5 on 2022-06-30 06:20

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('super_admin', '0007_odoo_notification'),
    ]

    operations = [
        migrations.AddField(
            model_name='odoo_notification',
            name='auth_user_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='odoo_notification_auth_user_login', to=settings.AUTH_USER_MODEL),
        ),
    ]
